spring:
  application:
    name: FC Messaging Service
  profiles:
    active: ${ACTIVE_PROFILE:default}

twilio:
  accountSid: ${ACCOUNT_SID:none}
  authToken: ${AUTH_TOKEN:none}
  fromNumber: ${FROM_NUMBER:none}
